# .NET Core
# Build and test NET Core projects.

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  pool: 'Default'
  pushPreview: 'internal;nuget.org'
  nugetVersion: ""
  releaseSkip: 'true'

resources:
  repositories:
    - repository: templates
      type: github
      name: Amith211/azure-pipelines-templates
      ref: refs/heads/master
      endpoint: Amith211

stages:
- template: .net/stages/build.yml@templates
  parameters:
    dotNetCoreInstallerVersion: '2.2.300'
    pool: $(pool)
    
- template: .net/stages/test.yml@templates

## Preview release ##

- stage: DeployPreview
  displayName: 'Deploy Preview'
  jobs:
  - job: NugetPackPreview
    displayName: 'Pack Nuget preview'
    pool:
      name: $(pool)
      #vmImage: 'windows-latest'
    steps:
    - checkout: none
    - template: .net/steps/load-variables.yml@templates

    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.SourcesDirectory)'

    - task: Powershell@2
      name: SetNugetSemVerVersion
      displayName: SetNugetSemVerVersion
      inputs:
        targetType: inline
        script: |
            . $(Build.SourcesDirectory)/build/Set-NugetSemVersion.ps1
             Get-NugetVersion -IsPreview;

    - template: .net/steps/nuget-pack.yml@templates
      parameters:
        artifactName: 'nuget-preview'
        nugetPackageVersion: $(SetNugetSemVerVersion.nugetVersionOutput)

  - template: .net/jobs/nuget-push-to-azureArtifacts.yml@templates
    parameters:
      jobName: 'DeployNugetPreviewAzureArtifacts'
      jobDisplayName: 'Deploy Preview to Azure Artifacts'
      azureDevOpsOrg: 'Amith211'
      pool: ${{ variables.pool }}
      artifactName: 'nuget-preview'
      publishDevOpsFeed: '/b4573900-0d0d-4915-b6b5-cfc2fee08f7d'
      islegacyDevOpsUrl: true
      allowPackageConflicts: true
      environment: 'Preview'

    #   Use when YAML Gates are implemented 
    #  - template: .net/jobs/nuget-push-to-nuget.yml@templates
    #    parameters:
    #      jobName: 'DeployNugetPreview'
    #      jobDisplayName: 'Deploy to Nuget.org'
    #      pool: ${{ variables.pool }}
    #      artifactName: 'nuget-preview'
    #      nuGetServiceConnections: 'Nuget.org'
    #      allowPackageConflicts: true
    #      nugetPackageVersion: $(DeployRelease.SetNugetSemVerVersion.nugetVersionOutput)
    #      environment: 'Release'
  condition: >  
    or(ne(variables['Build.Reason'], 'PullRequest'),
        startswith(variables['Build.SourceBranch'], 'refs/heads/azure-pipelines-test') )
## condition - Don't run stage if pull request unless it's an azure-pipelines test branch'

## Stable Release ##

- stage: DeployRelease
  displayName: 'Deploy Release'
  jobs:
  - job: NugetPackRelease
    displayName: 'Pack Nuget Release'
    pool:
      name: ${{ variables.pool }}
      #vmImage: 'windows-latest'
    steps:
    - checkout: none
    - template: .net/steps/load-variables.yml@templates

    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.SourcesDirectory)'

    - task: Powershell@2
      name: SetNugetSemVerVersion
      displayName: SetNugetSemVerVersion
      inputs:
        targetType: inline
        script: |
            . $(Build.SourcesDirectory)/build/Set-NugetSemVersion.ps1
             Get-NugetVersion;

    - template: .net/steps/nuget-pack.yml@templates
      parameters:
        artifactName: 'nuget'
        nugetPackageVersion: $(SetNugetSemVerVersion.nugetVersionOutput)

  - template: .net/jobs/nuget-push-to-azureArtifacts.yml@templates
    parameters:
      jobName: 'DeployNugetAzureArtifacts'
      jobDisplayName: 'Deploy to Azure Artifacts'
      azureDevOpsOrg: 'Amith211'
      pool: ${{ variables.pool }}
      artifactName: 'nuget'
      publishDevOpsFeed: '/b4573900-0d0d-4915-b6b5-cfc2fee08f7d'
      islegacyDevOpsUrl: true
      allowPackageConflicts: true
      environment: 'Release'

  - template: .net/jobs/nuget-push-to-nuget.yml@templates
    parameters:
      jobName: 'DeployNuget'
      jobDisplayName: 'Deploy to Nuget.org'
      pool: ${{ variables.pool }}
      artifactName: 'nuget'
      nuGetServiceConnections: 'Nuget.org'
      allowPackageConflicts: true
      nugetPackageVersion: $(DeployRelease.SetNugetSemVerVersion.nugetVersionOutput)
      environment: 'Release'
  condition: > 
    and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), 
      or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        startswith(variables['Build.SourceBranch'], 'refs/heads/release/'),
        startswith(variables['Build.SourceBranch'], 'refs/heads/azure-pipelines-test')) )
 ##condition - run only if master or release otherwise it is a prerelease allreay deployed in previous stage